# See also https://github.com/EVerest/everest-core/tree/main/.github/workflows
# TODO: modify to reuse the above workflow to DRY up CI.

name: Build and test libtimer
on: 
  pull_request: {}
  workflow_dispatch:
    inputs:
      runner:
        description: Which runner to use
        type: choice
        default: 'ubuntu-22.04'
        required: true
        options:
          - 'ubuntu-22.04'
          - 'large-ubuntu-22.04-xxl'
  schedule:
    - cron: '22 13,1 * * *'
jobs:
  ci:
    name: Build, Lint and Test
    uses: everest/everest-ci/.github/workflows/continuous_integration.yml@v1.4.6
    permissions:
      contents: read
    secrets:
      coverage_deploy_token: ${{ github.token }}
    with:
      runner: ${{ inputs.runner || 'ubuntu-22.04' }}
      artifact_deploy_target_repo: EVerest/everest.github.io
      run_coverage: false
      do_not_run_coverage_badge_creation: true
      ctest_report_path: ctest-report
